// Objective-C API for talking to pangpang/poscore/possdk Go package.
//   gobind -lang=objc -prefix=P2 pangpang/poscore/possdk
//
// File is generated by gobind. Do not edit.

#ifndef __P2Pos_H__
#define __P2Pos_H__

@import Foundation;
#include "GoUniverse.h"


FOUNDATION_EXPORT NSString* P2PosCall(NSString* uri);

FOUNDATION_EXPORT void P2PosInit(NSString* contextDirectory);

#endif
