// Objective-C API for talking to pangpangjan/pos/sdk Go package.
//   gobind -lang=objc -prefix="P2" pangpangjan/pos/sdk
//
// File is generated by gobind. Do not edit.

#ifndef __P2Pos_H__
#define __P2Pos_H__

@import Foundation;
#include "Universe.objc.h"


@class P2PosCartInMemoryClient;
@class P2PosCatalogInMemoryClient;
@class P2PosOrderInMemoryClient;

@interface P2PosCartInMemoryClient : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (id)initWithRef:(id)ref;
// skipped field CartInMemoryClient.Carts with unsupported type: *types.Map

// skipped method CartInMemoryClient.AddItem with unsupported parameter or return types

// skipped method CartInMemoryClient.CreateCart with unsupported parameter or return types

// skipped method CartInMemoryClient.GetAllCarts with unsupported parameter or return types

// skipped method CartInMemoryClient.GetCart with unsupported parameter or return types

- (BOOL)removeCart:(int64_t)cartId userId:(int64_t)userId spotId:(int64_t)spotId error:(NSError**)error;
// skipped method CartInMemoryClient.RemoveItem with unsupported parameter or return types

// skipped method CartInMemoryClient.SetCoupon with unsupported parameter or return types

// skipped method CartInMemoryClient.SetCustomer with unsupported parameter or return types

// skipped method CartInMemoryClient.SetInfo with unsupported parameter or return types

// skipped method CartInMemoryClient.SetPayment with unsupported parameter or return types

@end

@interface P2PosCatalogInMemoryClient : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (id)initWithRef:(id)ref;
// skipped field CatalogInMemoryClient.Contents with unsupported type: *types.Slice

// skipped field CatalogInMemoryClient.Skus with unsupported type: *types.Slice

// skipped method CatalogInMemoryClient.GetContent with unsupported parameter or return types

// skipped method CatalogInMemoryClient.GetSku with unsupported parameter or return types

// skipped method CatalogInMemoryClient.SearchContents with unsupported parameter or return types

// skipped method CatalogInMemoryClient.SearchSkus with unsupported parameter or return types

@end

@interface P2PosOrderInMemoryClient : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (id)initWithRef:(id)ref;
// skipped field OrderInMemoryClient.Orders with unsupported type: *types.Map

// skipped method OrderInMemoryClient.Get with unsupported parameter or return types

// skipped method OrderInMemoryClient.GetAll with unsupported parameter or return types

// skipped method OrderInMemoryClient.PlaceOrder with unsupported parameter or return types

@end

FOUNDATION_EXPORT NSString* P2PosCall(NSString* uri);

FOUNDATION_EXPORT void P2PosInit(NSString* contextDir);

// skipped function NewCartInMemoryClient with unsupported parameter or return types


FOUNDATION_EXPORT P2PosCatalogInMemoryClient* P2PosNewCatalogInMemoryClient();

// skipped function NewOrderInMemoryClient with unsupported parameter or return types


#endif
