
// Objective-C API for talking to the following Go packages
//
//	pangpangjan/pos/sdk
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Pos_FRAMEWORK_H__
#define __Pos_FRAMEWORK_H__

#include "P2Pos.objc.h"
#include "Universe.objc.h"

#endif
