
// Objective-C API for talking to the following Go packages
//
//	pangpang/poscore/possdk
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Pos_H__
#define __Pos_H__

#include "P2Pos.h"
#include "GoUniverse.h"

#endif
